
language: ruby

bundler_args: --without production development

before_script:
  - export RAILS_ENV=test
  - bundle exec rails db:schema:load RAILS_ENV=test

script: bundle exec rspec

rvm:
  - 2.2.0